version: '1.x'
services:
  23rp01658:
    build: .
    ports:
      - "8086:80"
    volumes:
      - ./:/var/www/html
  mysql-iraguha:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=23rp_shareride_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql-iraguha
      - PMA_PORT=3306
    ports:
      - 8088:80